# Generated by Django 4.0.4 on 2022-05-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField(verbose_name='ID')),
                ('match_group', models.CharField(max_length=1, verbose_name='Group')),
                ('match_date', models.DateField(verbose_name='Date')),
                ('match_time', models.TimeField(verbose_name='Time')),
                ('team_1', models.CharField(max_length=50, verbose_name='Home')),
                ('team_2', models.CharField(max_length=50, verbose_name='Away')),
            ],
        ),
    ]
