# Generated by Django 4.0.4 on 2022-05-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='match_id',
        ),
    ]
