# Generated by Django 4.0.4 on 2022-05-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_remove_matches_match_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matches',
            options={'verbose_name_plural': 'Matches'},
        ),
    ]
