# Generated by Django 4.0.4 on 2022-05-19 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictions', '0001_initial'),
        ('matches', '0003_alter_matches_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matches',
            new_name='Match',
        ),
    ]
